[package]
name = "dqcmap-circuit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "dqcmap_circuit"
doctest = false

[dependencies]
hashbrown.workspace = true
pyo3.workspace = true
